### ISSUE TITLE
Short term roadmap for v0.5

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#48]
From the 22/03 meeting with @GrandSchtroumpf, here is a short term roadmap/todos for remix-plugin. 
Please comment it below if you'd like to add/remove items.

 - [x] check all the remaining issues

 - [x] make sure the API for plugin developer is stable enough and will likely not change

 - [x] check the README ( for plugin developer ) and make sure everything is needed (including link to tutorials for uploading to ipfs and full API description)

 - [x] write a README for updating old remix-plugin to new API

 - [x] update remix-alpha

 - [x] send mail to plugin owner for giving update and support for moving to new API

____________

 - [x] make sure the API for remix-plugin implementers is stable enough and will likely not change

 - [x] create a README and onboard EtherAtom for implementing it  (that's new)

____________

 - [ ] ~~develop ipfs / (swarm?) dropzone for seamlessly deploy to ipfs and record the hash to a blockchain (testchain)~~

 - [ ] ~~develop a daemon used by plugin owner for sharing plugins resources (getting hash from blockchain and pulling the content from ipfs)~~
